version: "3.8"
services:
  app:
    build: .
    command: python app.py
    ports:
      - 5000:5000
    volumes:
      - .:/python-flask
  mysql:
    image: mysql:5.7
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: users
      MYSQL_USER: flaskapp
      MYSQL_PASSWORD: password
    ports:
    - 3306:3306

volumes:
  mysql_data:
