version: "3.8"
services:
  app:
    build: .
    command: python app.py
    ports:
      - 8080:5000
    volumes:
      - .:/python-flask
  mysql:
    platform: linux/x86_64
    image: mysql:5.7
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: users
      MYSQL_USER: flaskapp
      MYSQL_PASSWORD: password
    ports:
    - 3306:3306
  mongo:
    image: mongo
    volumes:
    - mongo_data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: flaskapp
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: test
  mongo-express:
    image: mongo-express
    ports:
      - 8888:8081
    environment:
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_MONGODB_PORTL: 27017
      ME_CONFIG_MONGODB_AUTH_DATABASE: admin
      ME_CONFIG_MONGODB_ADMINUSERNAME: flaskapp
      ME_CONFIG_MONGODB_ADMINPASSWORD: password
      ME_CONFIG_MONGODB_URL: mongodb://flaskapp:password@mongo:27017/
    depends_on:
      - mongo

volumes:
  mysql_data:
  mongo_data:
